spring:
  profiles:
    active: alpha
  OAuth2:
    google:
      url: https://accounts.google.com/o/oauth2/v2/auth
      client-id: 536621338256-o26l886k00265kcqtdgei2shgdh1dud6.apps.googleusercontent.com
      client-secret: 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
      redirect_uri: http://localhost:8080/auth/google/callback
      scope: https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 536621338256-o26l886k00265kcqtdgei2shgdh1dud6.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile
# OAuth

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/romantic_weapon?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: alpha
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://3.86.252.148:3306/romantic_weapon?useUnicode=yes&characterEncoding=UTF-8
    username: romantic
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

---

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
